FileVersion = 1
Projects = {ZenIDE = {Path = "."}, GLFW = {Path = "vendor/glfw-beef"}, ImGui = {Path = "vendor/imgui-beef"}, ImGuiImplGlfw = {Path = "vendor/imgui-beef/ImGuiImplGlfw"}, ImGuiImplOpenGL3 = {Path = "vendor/imgui-beef/ImGuiImplOpenGL3"}}

[Workspace]
StartupProject = "ZenIDE"
