FileVersion = 1
Dependencies = {corlib = "*", GLFW = "*", ImGui = "*", ImGuiImplGlfw = "*", ImGuiImplOpenGL3 = "*"}

[Project]
Name = "ZenIDE"
StartupObject = "ZenIDE.Program"

[Configs.Debug.Win64]
PostBuildCmds = ["CopyFilesIfNewer(\"$(ProjectDir)/resources\", \"$(BuildDir)\")"]
